import { FormEvent, useState } from 'react';
import { ArrowUpRight, Check, ChevronDown, CircleCheck, LineChart, Menu, X } from 'lucide-react';

const auditChecks = [
  ['Account structure', 'Campaigns, naming, settings, and budget flow.'],
  ['Keyword strategy', 'Match types, wasted spend, and negative keywords.'],
  ['Bidding & budget', 'Whether the account is buying the right outcomes.'],
  ['Ad copy & assets', 'Message quality, extensions, and relevance.'],
  ['Conversion tracking', 'Whether the numbers can actually be trusted.'],
  ['Landing page alignment', 'The handoff from click to qualified lead.'],
];

const faqs = [
  ['Will you change my account without asking?', "No. The audit is read-only. You get the findings, then decide what happens next."],
  ['I already have an agency. Is this awkward?', 'Not at all. Think of it as an independent second set of eyes you can share with your current team.'],
  ['What if I do not like what you find?', 'You keep the report either way. There is no obligation to continue.'],
  ['How fast do you respond?', 'Within one business day. If an account is actively spending, we keep the communication direct.'],
];

function Brand() { return <a className="brand" href="/"><span className="brand-mark">A</span><span>AdLovers<span className="brand-dot">.</span>online</span></a>; }

function Header({ agency }: { agency: boolean }) {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="nav-shell"><Brand /><nav className={open ? 'nav-links open' : 'nav-links'}><a href="#services" onClick={() => setOpen(false)}>Services</a><a href="#how-it-works" onClick={() => setOpen(false)}>How it works</a><a href="#about" onClick={() => setOpen(false)}>About</a><a href="#faq" onClick={() => setOpen(false)}>FAQ</a><a className={agency ? 'nav-active' : ''} href="/agencies" onClick={() => setOpen(false)}>For agencies <ArrowUpRight size={15}/></a></nav><a className="button button-small header-cta" href="#contact">{agency ? 'Book a call' : 'Get your free audit'}</a><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X/> : <Menu/>}</button></div></header>;
}

function TrendVisual() { return <div className="trend-visual" aria-label="Abstract chart showing improved campaign performance"><div className="chart-label">account signal <span>+42%</span></div><svg viewBox="0 0 520 300" role="img"><path className="chart-grid" d="M20 50H500M20 125H500M20 200H500M100 20V270M220 20V270M340 20V270M460 20V270"/><path className="chart-line ghost" d="M20 218 C90 180, 112 222, 170 190 S255 205, 300 158 S380 170, 430 130 S475 151, 500 102"/><path className="chart-line" d="M20 238 C74 228, 100 205, 148 214 S220 190, 264 172 S336 185, 379 122 S445 118, 500 53"/><circle className="chart-point" cx="500" cy="53" r="7"/></svg><div className="chart-foot"><span>before</span><span>after</span></div></div>; }

function SectionLabel({ children }: { children: string }) { return <p className="section-label">{children}</p>; }
function CTA({ children, href = '#contact' }: { children: string; href?: string }) { return <a className="button" href={href}>{children}<ArrowUpRight size={17}/></a>; }

function SMBHome() {
  return <><Header agency={false}/><main>
    <section className="hero section-pad"><div className="hero-copy"><SectionLabel>Google Ads, without the fog</SectionLabel><h1>A second opinion on your Google Ads account, without the agency overhead.</h1><p className="hero-lede">I audit and manage Google Ads accounts for small businesses. One specialist, direct communication, and a fraction of what agencies charge for the same work.</p><div className="hero-actions"><CTA>Get your free account audit</CTA><a className="text-link" href="#how-it-works">See how it works <ArrowUpRight size={16}/></a></div><div className="trust-line"><CircleCheck size={16}/> Read-only access is enough <span>•</span> No sales call required</div></div><TrendVisual/></section>
    <section className="proof-strip"><div><strong>Direct access</strong><span>No account manager layer</span></div><div><strong>Plain English</strong><span>Prioritized findings, not fluff</span></div><div><strong>One specialist</strong><span>Your account stays with me</span></div></section>
    <section id="services" className="section-pad content-section"><div className="section-intro"><SectionLabel>What I look at</SectionLabel><h2>A practical review of the things that make or break a campaign.</h2></div><div className="audit-grid">{auditChecks.map(([title, text]) => <div className="audit-item" key={title}><span className="audit-number">0{auditChecks.indexOf([title, text] as never)+1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><p className="fine-print">No jargon-heavy PDF. No upsell pressure. The findings are yours to use however you want.</p></section>
    <section id="about" className="split-section"><div className="split-visual"><span className="stamp">AD<br/>LOVERS</span><div className="portrait-placeholder">RB</div></div><div className="split-copy"><SectionLabel>Why work directly</SectionLabel><h2>Your budget should reach the person doing the work.</h2><p>Most of what you pay an agency for covers people who never touch your account: account managers, sales teams, and office overhead. When you work directly with me, you get the specialist actually managing your campaigns.</p><p>That is not a knock on agencies. Some businesses need a full team. It simply means a smaller business should not have to pay for structure it does not use.</p><div className="signature"><strong>Rafael Braga</strong><span>Senior Google Ads specialist</span></div></div></section>
    <section id="how-it-works" className="section-pad process-section"><div className="section-intro centered"><SectionLabel>How it works</SectionLabel><h2>Three steps. No theatre.</h2></div><div className="process-grid"><div><span>01</span><h3>Share access</h3><p>Read-only is enough. Tell me what you want the account to do better.</p></div><div><span>02</span><h3>I review it</h3><p>You get a clear, prioritized report within 3 business days.</p></div><div><span>03</span><h3>You decide</h3><p>Implement it yourself, hand it to your agency, or talk to me about management.</p></div></div></section>
    <section className="offer-section"><div><SectionLabel>Start with clarity</SectionLabel><h2>Free initial audit.</h2><p>See what is happening inside your account before you commit to anything. If you want ongoing management afterward, retainers start at $297/month.</p></div><CTA>Request your free audit</CTA></section>
    <FAQ/><Contact smb/>
  </main><Footer/></>;
}

function Agencies() {
  return <><Header agency/><main><section className="hero agency-hero section-pad"><div className="hero-copy"><SectionLabel>White-label Google Ads capacity</SectionLabel><h1>Your accounts get a senior specialist, not a junior rotating through 40 clients.</h1><p className="hero-lede">Add experienced Google Ads execution to your delivery team without another full-time hire, another layer of overhead, or another client handoff.</p><div className="hero-actions"><CTA>Book a discovery call</CTA><a className="text-link" href="#agency-services">See the offer suite <ArrowUpRight size={16}/></a></div><div className="trust-line"><CircleCheck size={16}/> US timezone overlap <span>•</span> White-label ready <span>•</span> Senior delivery</div></div><div className="agency-note"><LineChart size={28}/><p>Capacity relief<br/><strong>without margin compression.</strong></p><span>Fractional media buying for agencies that need more hands, not more hierarchy.</span></div></section><section className="proof-strip agency-strip"><div><strong>Capacity relief</strong><span>Take on more accounts</span></div><div><strong>Margin expansion</strong><span>Lower delivery overhead</span></div><div><strong>Zero overhead</strong><span>No payroll or bench</span></div></section><section id="agency-services" className="section-pad content-section"><div className="section-intro"><SectionLabel>Offer suite</SectionLabel><h2>One partner, three ways to extend your delivery team.</h2></div><div className="offer-list"><div><span>01</span><div><h3>Productized Google Ads Audit</h3><p>A fixed-fee account audit your team can sell as an entry offer or use to rescue a stuck account. Clear priorities, no bloated report.</p></div><strong>$297–$497</strong></div><div><span>02</span><div><h3>Dedicated white-label media buying</h3><p>A fractional senior media buyer for ongoing campaign management, optimization, and client-ready updates.</p></div><strong>$500–$2,500/mo</strong></div><div><span>03</span><div><h3>Tracking & infrastructure setup</h3><p>GTM, GA4, Enhanced Conversions, and server-side tracking as a focused setup or a retainer add-on.</p></div><strong>Scoped</strong></div></div></section><section className="agency-callout"><div><SectionLabel>Built for agency economics</SectionLabel><h2>Sell confidence. Deliver with a better margin.</h2></div><p>Position this as fractional senior execution, not cheap overseas labour. Your client sees continuity. Your team gets capacity. Your P&amp;L keeps the difference.</p></section><FAQ/><Contact/></main><Footer/></>;
}

function FAQ() { const [active, setActive] = useState(0); return <section id="faq" className="section-pad faq-section"><div className="section-intro"><SectionLabel>Questions, answered</SectionLabel><h2>Nothing hidden in the handoff.</h2></div><div className="faq-list">{faqs.map(([q,a], i) => <button className={active === i ? 'faq-item active' : 'faq-item'} key={q} onClick={() => setActive(active === i ? -1 : i)}><span><strong>{q}</strong>{active === i && <em>{a}</em>}</span><ChevronDown size={19}/></button>)}</div></section>; }

function Contact({ smb = false }: { smb?: boolean }) { const [sent, setSent] = useState(false); const submit = (e: FormEvent) => { e.preventDefault(); setSent(true); }; return <section id="contact" className="contact-section"><div className="contact-copy"><SectionLabel>{smb ? 'No pressure' : 'Let’s talk capacity'}</SectionLabel><h2>{smb ? 'Ready for an honest look at your account?' : 'Need a senior media buyer in the room?'}</h2><p>{smb ? 'Request your audit. No sales call required.' : 'Tell me what your team is carrying. I will tell you where I can take weight off.'}</p></div>{sent ? <div className="success-state"><CircleCheck size={30}/><h3>Message received.</h3><p>I will get back to you within one business day.</p></div> : <form onSubmit={submit}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>What are you working on?<textarea required placeholder="A few lines is enough."/></label><button className="button" type="submit">{smb ? 'Request my audit' : 'Book a discovery call'}<ArrowUpRight size={17}/></button></form>}</section>; }
function Footer() { return <footer><Brand/><p>Senior Google Ads execution, without the unnecessary layers.</p><div><a href="/">For businesses</a><a href="/agencies">For agencies</a><a href="#contact">Contact</a></div></footer>; }
export default function App() { const agency = window.location.pathname.startsWith('/agencies'); return agency ? <Agencies/> : <SMBHome/>; }
